db_path:
  permanent_path: "/app/storage/private/faces/permanent"
  semi_temporary_path: "/app/storage/private/faces/semi-temporary"
  temporary_path: "/app/storage/private/faces/temporary"
  active_db_path: "/app/storage/private/faces/active"

deepface_settings:
  model_name: "Facenet512"
  detector_backend: "yolov8m"
  face_score_threshold: 0.7
  recognition_threshold: 0.6 # 0.5 for VGG-Face, 0.6 for Facenet512

cameras:
  - name: "webcam1"
    url: "rtsp://mediamtx:8554/input/webcam1"
    enabled: true
    detect_fps: 5
    resize: [640, 360]
    show_frame: false

snapshot:
  enabled: true
  output_dir: '/app/storage/private/snapshots'

mqtt:
  enabled: true
  event_topic_prefix: "facerecognition/events"
  register_topic: "facerecognition/register"
  command_topic_prefix: "facerecognition/cmd"
  state_topic_prefix: "facerecognition/state"
