detection_settings:
  model_path: "/app/storage/private/models/weight.hdf5"
  output_dir: '/app/storage/private/output'

cameras:
  - name: "webcam1"
    url: "rtsp://localhost:8554/input/webcam1"
    enabled: true
    detect_fps: 5
    resize: [224, 224]
    show_frame: false

snapshot:
  enabled: true
  output_dir: '/app/storage/private/snapshots'

mqtt:
  enabled: true
  event_topic_prefix: "sexualdetection/events"
  command_topic_prefix: "sexualdetection/cmd"
  state_topic_prefix: "sexualdetection/state"
