detection_settings:
  model_path: "/app/storage/private/models/weight.hdf5"
  output_dir: '/app/storage/private/output'
  resize: [224, 224]
  detect_fps: 5

snapshot:
  enabled: true
  output_dir: '/app/storage/private/snapshots'

mqtt:
  enabled: true
  event_topic_prefix: "sexual_detection/events"
  command_topic_prefix: "sexual_detection/cmd"
  state_topic_prefix: "sexual_detection/state"
